FROM node:22 AS build

WORKDIR /app

COPY . /app

WORKDIR /app/v2/web
RUN npm ci
RUN npm run build

FROM node:22

WORKDIR /app/v2/web

COPY --from=build /app /app

EXPOSE 3000

CMD ["npm", "run", "start", "--", "--hostname", "0.0.0.0", "--port", "3000"]
